# Generated by Django 2.2.19 on 2022-08-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220806_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsRecipes',
            new_name='RecipesIngredients',
        ),
        migrations.RemoveConstraint(
            model_name='recipesingredients',
            name='unique_ingredients_recipes',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название ингредиента'),
        ),
        migrations.AddConstraint(
            model_name='recipesingredients',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'ingredient_id'), name='unique_recipes_ingredients'),
        ),
    ]
