# Generated by Django 3.2.15 on 2022-08-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220811_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipesIngredients',
            new_name='IngredientInRecipe',
        ),
        migrations.RenameModel(
            old_name='RecipesTags',
            new_name='TagInRecipe',
        ),
    ]
