# Generated by Django 3.2.15 on 2022-08-17 19:27

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.IntegerField(validators=[recipes.validators.validate_integer_greater_zero]),
        ),
    ]
