# Generated by Django 3.2.15 on 2022-08-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220821_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
